-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "tray" TYPE INTEGER USING CASE WHEN "tray" = true THEN 0 ELSE NULL END;
ALTER TABLE "Customer" ALTER COLUMN "crane" TYPE INTEGER USING CASE WHEN "crane" = true THEN 0 ELSE NULL END;
ALTER TABLE "Customer" ALTER COLUMN "semi" TYPE INTEGER USING CASE WHEN "semi" = true THEN 0 ELSE NULL END;
ALTER TABLE "Customer" ALTER COLUMN "semiCrane" TYPE INTEGER USING CASE WHEN "semiCrane" = true THEN 0 ELSE NULL END;
ALTER TABLE "Customer" ALTER COLUMN "tolls" TYPE BOOLEAN USING CASE WHEN "tolls" IS NOT NULL THEN true ELSE false END; 